version: "3.9"

services:
  backend:
    image: krish1406/ridex-backend:latest
    container_name: ridex-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    image: krish1406/ridex-frontend:latest
    container_name: ridex-frontend
    ports:
      - "80:5173"
    depends_on:
      - backend
    restart: unless-stopped